version: '3.7'
services:
    app:
        build:
            args:
                user: docker-data
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel10
        container_name: laravel10-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - './:/var/www'
        networks:
            - laravel10
    postgres:
        image: 'postgres:14.7-alpine'
        container_name: '${PROJECT_NAME}-postgres'
        volumes:
            - './docker-compose/postgres:/var/lib/postgresql/data'
        environment:
            - 'POSTGRES_USER=${POSTGRES_USER}'
            - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
            - 'POSTGRES_DB=${POSTGRES_DB}'
            - 'POSTGRES_HOST_AUTH_METHOD: trust'
        ports:
            - '54320:5432'
    nginx:
        image: 'nginx:alpine'
        container_name: laravel10-nginx
        restart: unless-stopped
        environment:
            - NGINX_SERVER_NAME=laravel10.app
            - NGINX_MAX_BODY=100M
        ports:
            - '8001:80'
        volumes:
            - './:/var/www'
            - './docker-compose/nginx:/etc/nginx/conf.d/'
        networks:
            - laravel10
    redis:
        image: 'redis:7.2-rc1-alpine'
        container_name: '${PROJECT_NAME}-redis'
        ports:
            - '6378:6379'
networks:
    laravel10:
        driver: bridge
