version: "3"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
            image: laravel10
            container_name: laravel10-app
            restart: unless-stopped
            working_dir: /var/www/
            volumes:
                - ./:/var/www
            networks:
                - laravel10

              
    nginx:
        image: nginx:alpine
        container_name: laravel10-nginx
        restart: always
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel10

networks:
    laravel10:
    driver: bridge
